import { Invoice } from '@prisma/client';
import {
  Body,
  Container,
  Head,
  Heading,
  Html,
  Img,
  Link,
  Tailwind,
  Text,
} from '@react-email/components';

interface VercelInviteUserEmailProps {
  code: string;
  downloadUrl: string;
  dueDate: string;
  id: string;
  invoice_id: string;
  totalAmount: number;
}
const baseUrl = process.env.VERCEL_URL
  ? `https://${process.env.VERCEL_URL}`
  : 'https://mentorhq.app';

export const InvoiceEmail = ({
  code,
  downloadUrl,
  dueDate,
  invoice_id,
  totalAmount,
}: VercelInviteUserEmailProps) => {
  const previewText = `Invoice from Simen`;
  const logo = `${baseUrl}/logos/logo_text_color.png`;

  return (
    <Html>
      <Tailwind>
        <Body className="bg-gray-100 p-6">
          <Head>
            <title>{previewText}</title>
          </Head>
          <Container className="max-w-xl mx-auto bg-white rounded-lg p-6 border shadow-md">
            <Container className="text-center mb-6">
              <Img
                alt="DigitalFairytales Logo"
                className="mx-auto mb-4"
                height={'100%'}
                src={logo}
                width={'100%'}
              />
              <Heading as="h1" className="text-2xl font-bold">
                DigitalFairytales - Simen Daehlin
              </Heading>
              <hr className="my-4 border-gray-300" />
            </Container>

            <Container className="text-center mb-6">
              <Text className="text-lg font-semibold">
                Your Invoice for ${totalAmount} is Ready!
              </Text>
              <Text>
                Please review and complete your payment by{' '}
                <span className="font-bold">${dueDate}</span>.
              </Text>
            </Container>

            <Container className="text-center mb-4">
              <Link
                className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
                href={downloadUrl}
                target="_blank"
              >
                View Invoice
              </Link>
            </Container>

            <Container className="text-center">
              <Text className="text-sm">Invoice ${invoice_id}</Text>
              <Link
                className="text-sm text-blue-500 hover:underline"
                href={downloadUrl}
                target="_blank"
              >
                View Invoice
              </Link>
              <Text>
                Your access code is <br />
                <span className="font-bold">{code}</span>
              </Text>
            </Container>

            <Container className="text-center mt-6">
              <Text className="text-sm">DigitalFairytales - Simen Daehlin</Text>
              <Text className="text-sm">Phone: +447480887171</Text>
              <Link
                className="text-sm text-blue-500 hover:underline"
                href="https://mentorhq.app"
              >
                Generated by MentorHQ.app
              </Link>
            </Container>
          </Container>
        </Body>
      </Tailwind>
    </Html>
  );
};

export default InvoiceEmail;
